### ISSUE TITLE
NameError: uninitialized constant ActionView::Template::Handlers::ERB::Erubi

### ISSUE THREAD

**Issue by rgaufman** [errbit/errbit#1456] opened 2019-11-23 15:11 UTC
### Step 2: Describe your environment

  * Errbit version: latest master
  * OS: Ubuntu 18.04
  * Ruby: 2.6.5

#### Steps to reproduce:

  1. Follow installation instructions

#### Observed Results:

```
$ bundle exec rake errbit:bootstrap
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
rake aborted!
NameError: uninitialized constant ActionView::Template::Handlers::ERB::Erubi
/var/lib/gems/2.6.0/gems/haml-5.0.4/lib/haml/railtie.rb:37:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:27:in `each'
/var/lib/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/var/lib/gems/2.6.0/gems/haml-5.0.4/lib/haml/railtie.rb:22:in `block in <class:Railtie>'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/home/deployer/errbit/config/environment.rb:19:in `<top (required)>'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.6.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => errbit:bootstrap => db:seed => environment
(See full trace by running task with --trace)
```

#### Expected Results:

  * The bootstrap should succeed

**Comment by bwlang** [comment] 2019-12-02 18:10
this was fixed in PR #1455

**Closed** 2019-12-02 18:11 UTC

**Comment by jaswinder97** [comment] 2020-03-14 11:48
I am still facing this issue. 

Ubuntu: 18.04.3
ruby: 2.6.3

**Comment by stevecrozz** [comment] 2020-03-14 20:32
@jaswinder97 I'm trying, with the same version of Ruby but I cannot reproduce this issue. You're using the latest source code from the master branch? Or one of the releases? If anyone can repro this issue in a docker container and provide steps that could help me track it down.

**Comment by tthommmm** [comment] 2020-03-26 20:14
I'm having this issue when trying to add gem 'haml' to my gemfile.  Server doesn't run and my haml files aren't being found by render partial: 'partial_path'

**Comment by aliammaar** [comment] 2022-02-01 08:37
> OS Catalina 10.15.3

+1

**Comment by burnettk** [comment] 2022-02-01 14:23
@aliammaar could you provide reproduction steps using docker?
