### ISSUE TITLE
Email says "This error has occured 0 times" for the first occurance

### ISSUE THREAD

**Issue by funglaub** [errbit/errbit#982] opened 2015-10-20 15:41 UTC
If you enable email notifications, the email says "This error occured 0 times" for the first exception that errbit catches.

Shouldn't that be "1 times"?

**Comment by stevecrozz** [comment] 2015-10-20 15:47
Yeah zero must be wrong. It sounds like a bug.

**Comment by stevecrozz** [comment] 2015-12-23 19:30
@funglaub Are you still seeing this issue? I went to track it down today, but I'm no longer seeing it.

**Comment by stevecrozz** [comment] 2015-12-28 20:21
I'm closing this because I cannot reproduce it. I think its been fixed since this issue first came up.

**Closed by stevecrozz** 2015-12-28 20:21 UTC
Labels: bug
