### ISSUE TITLE
NameError: uninitialized constant IssueTrackers

### ISSUE THREAD

**Issue by kubaaa** [errbit/errbit#926] opened 2015-08-26 16:12 UTC
I update Errbit to last versions. If i click link http://errbit.net/apps, i get error  NameError: uninitialized constant IssueTrackers

activesupport-4.1.12/lib/active_support/inflector/methods.rbmethods.rb:238→ const_get
activesupport-4.1.12/lib/active_support/inflector/methods.rbmethods.rb:238→ block in constantize
activesupport-4.1.12/lib/active_support/inflector/methods.rbmethods.rb:236→ each
activesupport-4.1.12/lib/active_support/inflector/methods.rbmethods.rb:236→ inject
...
mongoid-5.0.0.beta/lib/mongoid/relations/accessors.rbaccessors.rb:100→ block in get_relation
mongoid-5.0.0.beta/lib/mongoid/threaded/lifecycle.rblifecycle.rb:89→ _building
mongoid-5.0.0.beta/lib/mongoid/relations/accessors.rbaccessors.rb:99→ get_relation
mongoid-5.0.0.beta/lib/mongoid/relations/accessors.rbaccessors.rb:187→ block in getter
app/models/app.rbapp.rb:129→ issue_tracker_configured?
draper-2.1.0/lib/draper/delegation.rbdelegation.rb:10→ issue_tracker_configured?
app/helpers/apps_helper.rbapps_helper.rb:47→ block in detect_any_apps_with_attributes
app/helpers/apps_helper.rbapps_helper.rb:44→ each
app/helpers/apps_helper.rbapps_helper.rb:44→ detect_any_apps_with_attributes
app/helpers/apps_helper.rbapps_helper.rb:15→ any_github_repos?
app/views/apps/index.html.hamlindex.html.haml:9→ _app_views_apps_index_html_haml__2492920191333893560_70247947053460

**Comment by haobole** [comment] 2015-08-26 17:16
:+1:

**Comment by stevecrozz** [comment] 2015-08-26 17:21
Thanks for the report @kubaaa . This could be due to a recent change I made in cleaning out a bunch of old migrations. Can you verify that you have followed these instructions?
https://github.com/errbit/errbit#upgrading-errbit-beyond-v040

**Comment by kubaaa** [comment] 2015-08-27 09:46
Yes. I run rake db:migrate on server. I use Redmine Tracker in my server.  The server has created an early app. If I try to view the app or to edit, I get the above error. To deploy, use this manual https://github.com/errbit/errbit/blob/master/docs/deployment/capistrano.md

**Comment by stevecrozz** [comment] 2015-08-27 17:33
@kubaaa Can you please show me the output of `rake db:version` for your environment and also the git sha1 you have deployed?

**Comment by projectorial** [comment] 2015-08-31 08:46
bundle exec rake db:version
rake aborted!
Don't know how to build task 'db:version'

(See full trace by running task with --trace)

**Comment by kubaaa** [comment] 2015-08-31 10:40
bundle exec rake db:version
rake aborted!
Don't know how to build task 'db:version'

(See full trace by running task with --trace)

**Comment by stevecrozz** [comment] 2015-08-31 17:16
@kubaaa that's not what I expected at all. Are you available to pop into https://gitter.im/errbit/errbit to chat?

**Comment by stevecrozz** [comment] 2015-09-04 00:10
The only explanation I can come up with is you're on an outdated revision of errbit which has a bug. I'm expecting that you need to git checkout v0.4.0, run migrations, then pull the latest code from master.
```
$ git checkout v0.4.0
$ bundle exec rake db:version
20150527202629
# since 20150527202629 is greater than 20131011155638, I'm good to upgrade beyond v0.4.0
# https://github.com/errbit/errbit#upgrading-errbit-beyond-v040
# if your db version is too low, you must run migrations here before pulling new code
# using rake db:migrate
$ git checkout master && git pull --ff
```

**Comment by stevecrozz** [comment] 2015-09-15 19:01
Github user @j3ck had a similar issue and we found that he had somehow a partially migrated database. I would like to know the underlying cause, but for anyone who is running into this issue, this is the result of not having run or only partly run this migration: https://github.com/errbit/errbit/blob/v0.4.0/db/migrate/20131011155638_extract_issue_tracker.rb

**Comment by jeremywadsack** [comment] 2015-10-26 23:50
I've run into the same issue. How do I tell if a migration is run (or run a single migration)? I checked in the `data_migrations` collection but it doesn't have anything old:

```
rs-ds039017:PRIMARY> db.data_migrations.find()
{ "_id" : ObjectId("562ea12a3c550d0003000000"), "version" : "20150527202629" }
{ "_id" : ObjectId("562ea6933c550d0003000001"), "version" : "20150926035420" }
```

We started with an older version of errbit. It failed because MongoLabs upgraded everyone to MongoDB 3.0 and the mongoid driver didn't seem to support that. 

I tried upgrading to v0.4.0 but that still gave me authentication errors, which MongoLabs says is related to the wrong version.

So I deployed new code from `master` that was able to connect. I ran the migrations and it ran two of them (which are shown above). But there's no `20131011155638_extract_issue_tracker.rb` in the `db/migrate` folder on master. Why are migrations missing on master that were in a previous release?

**Comment by stevecrozz** [comment] 2015-10-27 00:07
@jeremywadsack You did find the right way to see if a migration has been run, and we can see from that output that 20131011155638 has not been run. The reason the migrations are not all present in the latest release is because upgrading to mongoid 5 left them broken. My rationale was since these were 2+ years old, most people had already run them and it would be safe to delete them. I thought users would be able to check out v0.4.0, run the migrations and then upgrade. But that turns out not to be the case because v0.4.0 doesn't even work in your environment. So now you're stuck.

This has affected enough people now to where I think I'm convinced of the need to at least port this one migration onto the latest errbit. It seems to be the only one causing issues for our users. That's now the action item in my mind.

**Comment by jeremywadsack** [comment] 2015-10-27 00:35
@stevecrozz Thanks for the quick response. If there's anything I can do to help on this let me know. We'd like to get our errbit back up and running. ;)

We installed this on April 2014 using what was likely master at the time. I recall updating it at least once since then and thought I also updated to master. I assume I would have run migrations, but perhaps I didn't. Would it have worked without them?

So I dug through some of the updates we made to our copy and it looks like we deployed 571a75854b2c49dcdff71b6e4177424ee66b0ba2 in which that migration was [a totally different beast]( https://github.com/errbit/errbit/blob/571a75854b2c49dcdff71b6e4177424ee66b0ba2/db/migrate/20131011155638_extract_issue_tracker.rb). So maybe the issue is that you [changed the migration but not the version](https://github.com/errbit/errbit/commit/8dbfda4566fbf24b73f6173967fb0d0de032d296)? I guess that's why you said we needed to upgrade to v0.4.0 first.

**Comment by stevecrozz** [comment] 2015-10-27 00:54
Hm. I don't recall having done that, but it looks like that did happen. Interestingly since this migration is not recorded in your db, the instructions would still have worked for you if you were able to run them on v0.4.0. If you had run the previous edition of that same migration and it was recorded in your db, then this would fail for that entirely separate reason. This is getting complicated, but I think we can still address the issue that you have right now by reintroducing this migration into the current codebase. I think it will be a simple matter to bring it in and make it compatible with mongoid5.

@jerefrer showed us how to do it in https://gitter.im/errbit/errbit when he said he changed App.collection.where to App.where. If you want to put in a PR that does this and verify that it fixes your wagon, then I'll pull it in and we can probably close this issue.

**Comment by stevecrozz** [comment] 2015-12-02 03:56
This issue should be behind us now that @jeremywadsack has restored the missing migration.

**Closed by stevecrozz** 2015-12-02 03:56 UTC
